name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master

    - name: Build Frontend container image
      run: docker build --tag website:frontend -f ./website-frontend/Dockerfile ./website-frontend

    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.0.0
      with:
        # Version of doctl to install
        version: latest
        # DigitalOcean API Token
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log into DigitalOcean doctl
      run: doctl registry login

    - name: Tag frontend image in registry
      run: docker tag website:frontend registry.digitalocean.com/website-registry/website:frontend

    - name: Push frontend image to registry
      run: docker push registry.digitalocean.com/website-registry/website:frontend