name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master

    - name: test
      run: echo -e "Testing the new pipeline"

    - name: Build Frontend container image
      run: docker build --tag website:frontend -f ./website-frontend/Dockerfile ./website-frontend